spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/horoscope_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: super-secret-key-for-horoscope-app-minimum-32-characters
  expiration: 86400000

server:
  port: 8080